import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import Footer from "@/components/footer/footer";
import AuthGuard from "@/components/auth/AuthGuard";

export const metadata = {
  title: "Store Manager",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.boxicons.com/fonts/basic/boxicons.min.css"
          rel="stylesheet"
        />
        {/* <link href="/web-icon-01.png" rel="icon" /> */}
      </head>
      <body>
        <AuthGuard>
          <Navbar />
          {children}
          <Footer />
        </AuthGuard>
      </body>
    </html>
  );
}
